### ISSUE TITLE
Не работает для меня

### ISSUE THREAD

**Issue by jslby** [novaws/pi_tor_socks#1]
Привет. Запуск проекта из образа стопорит загрузку в самом начале, когда показывается цветной квадрат.
При запуске проекта через install.sh - падает 3proxy. 1 раз подключилось к wifi, но при внесении изменений в настройки wifi - установил другое имя и пароль(8 символов) вафля упала и безвозвратно. Пробовал руками откатить конфиг - все равно не видно в списке подключений.

Raspberry Pi 3 B+

**Comment by novaws** [comment]
на Raspberry Pi 3 B+ - не тестирвоалось. у меня просто Raspberry Pi 3 B.
как падает 3proxy? лог?
касательно вафли проблема известная с тем что что то криво вносите  конфиг. пробелы или что то еще. у всех по разному.

**Comment by jslby** [comment]
не стартует служба dhcp. пишет что уже используется. Хотя в линуксе больше кода, и знаю как убить процесс. была проблема так же с тем, что не назначается IP, но ее решил удалением файла с pid.

**Comment by novaws** [comment]
там в качестве dhcp работает dnsmasq. проверьте запущен ли он.
посмотрите по логам если не запущен то почему.
