### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by cmaukr** [novaws/pi_tor_socks#2]
Привет у меня raspberry pi 3 b+ все поставил по wifi конект есть но интернета нет 
в статусе wifi админки 

Curent Mode - TOR Mode
Status TOR - Active
Status 3proxy - Down
Status DNS proxy - Active
Status 3G - Down 

Интернет на малинку по кабелю приходит - 3G модема нет 
В чем может быть проблема? 
Могу заплатить за настройку 
Спасибо за ответ

**Comment by novaws** [comment]
это нерпо не имеет отношения к релизу вообще.
тут файлы админки.
ии читайте внимательно. 100 раз уже писал на тему 3b+
